name: check build and lint

on:
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build
        run: |
          npm install
          npm run build
